networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}
volumes:
  mariadb:
    driver: ${VOLUMES_DRIVER}

services:
### PHP-FPM ##############################################
    php-fpm-8.2:
      container_name: php-fpm-${PHP_VERSION}
      build:
        context: ./php-fpm
        args:
          - PHP_VERSION=${PHP_VERSION}
          - http_proxy
          - https_proxy
          - no_proxy
      expose:
        - "9000"
      volumes:
        - ./php-fpm/config/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      networks:
        - backend

### NGINX Server #########################################
    nginx:
      container_name: nginx
      build:
        context: ./nginx
        args:
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        - ./nginx/conf.d/upstream${PHP_VERSION}.conf:/etc/nginx/conf.d/upstream.conf
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
      depends_on:
        - php-fpm-${PHP_VERSION}
      networks:
        - frontend
        - backend

### MariaDB ##############################################
    # mariadb:
      # build:
        # context: ./mariadb
        # args:
          # - http_proxy
          # - https_proxy
          # - no_proxy
          # - MARIADB_VERSION=${MARIADB_VERSION}
      # volumes:
        # - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
        # - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      # ports:
        # - "${MARIADB_PORT}:3306"
      # environment:
        # - TZ=${WORKSPACE_TIMEZONE}
        # - MYSQL_DATABASE=${MARIADB_DATABASE}
        # - MYSQL_USER=${MARIADB_USER}
        # - MYSQL_PASSWORD=${MARIADB_PASSWORD}
        # - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      # networks:
        # - backend
